def List():
    FF={"apple inc.": "AAPL",
    "apple": "AAPL",
    "alphabet inc.": "GOOGL",
    "google": "GOOGL",
    "microsoft corporation": "MSFT",
    "microsoft": "MSFT",
    "amazon inc.": "AMZN",
    "amazon": "AMZN",
    "meta platforms inc.": "FB",
    "meta": "FB",
    "facebook": "FB",
    "nvidia corporation": "NVDA",
    "nvidia": "NVDA",
    "intel": "INTC",
    "intel corporation": "INTC",
    "jpmorgan chase & co.": "JPM",
    "jpmorgan": "JPM",
    "bank of america corporation": "BAC",
    "bank of america": "BAC",
    "johnson & johnson": "JNJ",
    "the coca-cola company": "KO",
    "coca-cola": "KO",
    "exxon mobil corporation": "XOM",
    "exxon": "XOM",
    "boeing company": "BA",
    "boeing": "BA",
    "at&t inc.": "T",
    "at&t": "T",
    "spdr s&p 500 etf trust": "SPY",
    "pepsico, inc.": "PEP",
    "pepsi": "PEP",
    "procter & gamble company": "PG",
    "procter & gamble": "PG",
    "costco wholesale corporation": "COST",
    "costco": "COST",
    "chevron corporation": "CVX",
    "chevron": "CVX",
    "bp p.l.c.": "BP",
    "caterpillar inc.": "CAT",
    "caterpillar": "CAT",
    "general electric company": "GE",
    "general electric": "GE",
    "wells fargo & company": "WFC",
    "wells fargo": "WFC",
    "citigroup inc.": "C",
    "citigroup": "C",
    "goldman sachs group, inc.": "GS",
    "goldman sachs group": "GS",
    "morgan stanley": "MS",
    "pfizer inc.": "PFE",
    "pfizer": "PFE",
    "abbott laboratories": "ABT",
    "merck & co., inc.": "MRK",
    "merck": "MRK",
    "unitedhealth group incorporated": "UNH",
    "unitedhealth group": "UNH",
    "gilead sciences, inc.": "GILD",
    "gilead sciences": "GILD",
    "nike, inc.": "NKE",
    "nike": "NKE",
    "the walt disney company": "DIS",
    "disney": "DIS",
    "walt disney company": "DIS",
    "netflix, inc.": "NFLX",
    "netflix": "NFLX",
    "square, inc.": "SQ",
    "square": "SQ",
    "salesforce, inc.": "CRM",
    "salesforce": "CRM",
    "alibaba group holding limited": "BABA",
    "alibaba group": "BABA",
    "alibaba=": "BABA",
    "taiwan semiconductor manufacturing company": "TSM",
    "rio tinto group": "RIO",
    "rio tinto": "RIO",
    "spdr dow jones industrial average etf trust": "DIA",
    "ishares russell 2000 etf": "IWM",
    "invesco qqq trust": "QQQ",
    "vanguard total stock market etf": "VTI"}
    return FF